backend:
  name: git-gateway
  branch: main

media_folder: "src/static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "pages"
    label: "Stránky"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Šablona"
        name: "layout"
        widget: "select"
        options:
          - { label: "Standardní text", value: "default" }
          - { label: "Kontaktní formulář", value: "contact" }
        default: "default"

      # Společné pole pro všechny
      - { label: "Titulek", name: "title", widget: "string" }

      # Pole viditelné jen pro 'default'
      - label: "Hlavní text"
        name: "text-content"
        widget: "markdown"
        condition: { field: "layout", value: "default" }

      # Pole viditelná jen pro 'contact'
      - label: "Email"
        name: "email"
        widget: "string"
        condition: { field: "layout", value: "contact" }
      
      - label: "Telefon"
        name: "phone"
        widget: "string"
        condition: { field: "layout", value: "contact" }